---
include:
  - board: nice_nano
    shield: helix_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: nice_nano
    shield: helix_right nice_view_adapter nice_view
  - board: nice_nano
    shield: settings_reset