---
include:
  - board: nice_nano
    shield: helix_left nice_view_adapter nice_view
  - board: nice_nano
    shield: helix_right nice_view_adapter nice_view
  - board: nice_nano
    shield: settings_reset